### ISSUE TITLE
Improve conference dates on each card

### ISSUE THREAD

**Issue by luisFilipePT** [homeferences/website#3]
Right now we have this: 

![image](https://user-images.githubusercontent.com/9373787/76886644-05735f00-6879-11ea-9387-04b68542a16f.png)

It would be cool to have some checks like:
If its only one day show just that day
If its more that one day show `<start> to <end>`
and maybe improve a bit the time formatting and design (open to suggestions)

**Comment by coderbyheart** [comment]
See b59eb794bcad09e0f2639e37cfeaddd9ac28c9c3
