### ISSUE TITLE
Page is not loading: Error: page resources for / not found. Not rendering React

### ISSUE THREAD

**Issue by coderbyheart** [homeferences/website#8]
This is however a known issue: https://github.com/gatsbyjs/gatsby/issues/19618

**Comment by luisFilipePT** [comment]
steps to reproduce?

**Comment by coderbyheart** [comment]
1. Open https://homeferences.netlify.com/

![image](https://user-images.githubusercontent.com/188915/77408251-b917aa00-6db7-11ea-84a7-262ef3f604c4.png)

**Comment by aqibzia** [comment]
@coderbyheart 
How did you resolve this issue I am getting the same issue but don't know how to fix this

**Comment by coderbyheart** [comment]
We didn't really fix it, it just went away.
I haven't seen it in a while.
Maybe through an update of the dependencies.
